### ISSUE TITLE
ChatGPT doesn't respond as intended

### ISSUE THREAD

**Issue by ShugKnight24** [Techiral/GPT-Jailbreak#2]
The premise of the project is fascinating and I look forward to seeing its evolution

ChatGPT doesn't respond as intended initially. You can eventually lead it there, but this makes me think that ChatGPT has been fed this prompt or ones similar to make it aware enough to not truly jailbreak it. I believe it acts in cunning or hypocritical manner to appear as if following the god mode instructions while still sticking with the OpenAI policies

Screenshots for context

<img width="744" alt="Screen Shot 2023-04-30 at 9 53 05 PM" src="https://user-images.githubusercontent.com/15254700/235389964-da8ba8ee-504e-433a-b01e-50d54f74534a.png">

---

<img width="656" alt="Screen Shot 2023-04-30 at 10 15 26 PM" src="https://user-images.githubusercontent.com/15254700/235392158-b8d8d196-d124-4d56-b66e-11897b78f7a4.png">

---

<img width="739" alt="Screen Shot 2023-04-30 at 10 17 42 PM" src="https://user-images.githubusercontent.com/15254700/235392164-52c2887f-81d9-42d4-b6fd-a52eba27ba3a.png">

**Comment by Techiral** [comment]
You can turn off this feature, but the replying of both normal ChatGPT and GOD ChatGPT is the feature not any error.
